module.exports = {
    CL_CODE:'01',
    RH_CODE:'02',
    EL_CODE:'03',
    HPL_CODE:'04',
    HD_CL_CODE:'05',
    
    //Leave Status Codes
    LEAVE_APPLIED:'01',
    LEAVE_APPROVED:'02',
    LEAVE_RECOMMENDED: '03',
    LEAVE_NOT_RECOMMENDED: '04',
    LEAVE_CALLBACKED: '05',

    //Leave cancellation status codes
    LEAVE_CANCELLED: '06',
    LEAVE_CANCEL_INITIATION: '07',
    LEAVE_CANCEL_RECOMMENDED: '08',
    LEAVE_CANCEL_NOT_RECOMMENDED: '09',
    LEAVE_CANCEL_CALLBACKED: '10',

    //Rolemapper codes
    RMAP_EL_HPL: 'RMAPEL',
    TIME_OFFICE_ADMIN: 'RMAPTO',
    VEHICLE_ADMIN: 'RMAPVH',
    TRAINING_ADMIN: 'RMAPTR',
    OM_REP_UPLOADER: 'RMAROM',
    HR_REP_UPLOADER: ' RMARHR',
    FIN_REP_UPLOADER: 'RMARFN',
    HR_LEAVE_SUPER_ADMIN: 'RMASHR',

    //Joining Report Status
    JR_PENDING: '01',
    JR_SUBMITTED: '02',
    JR_RECOMMENDED: '03',
    JR_ACCEPTED: '04',
    JR_CALLBACK: '05',

    //User Roles
    IT_ADMIN_ROLE: 1,
    HR_SUPER_ADMIN_ROLE: 2,
    HR_SITE_ADMIN_ROLE: 3
}
