module.exports = {
    CL_CODE:'01',
    RH_CODE:'02',
    EL_CODE:'03',
    HPL_CODE:'04',
    HD_CL_CODE:'05',
    
    LEAVE_APPLIED:'01',
    LEAVE_APPROVED:'02',
    LEAVE_RECOMMENDED: '03',
    LEAVE_NOT_RECOMMENDED: '04',
    LEAVE_CALLBACKED: '05',
    LEAVE_CANCELLED: '06',

    RMAP_EL: 'RMAPEL',
    RMAP_HPL: 'RMAPML',

    //User Roles
    IT_ADMIN_ROLE: 1,
    HR_SUPER_ADMIN_ROLE: 2,
    HR_SITE_ADMIN_ROLE: 3
}
