module.exports = {
    CL_CODE:'01',
    RH_CODE:'02',
    EL_CODE:'03',
    HPL_CODE:'04',
    HD_CL_CODE:'05',
    
    LEAVE_APPLIED:'01',
    LEAVE_APPROVED:'02',
    LEAVE_RECOMMENDED: '03',
    LEAVE_NOT_RECOMMENDED: '04',
    LEAVE_CALLBACKED: '05',
    LEAVE_CANCELLED: '06',

    RMAP_EL_HPL: 'RMAPEL',
    TIME_OFFICE_ADMIN = 'RMAPTO',
    VEHICLE_ADMIN = 'RMAPVH',
    TRAINING_ADMIN = 'RMAPTR',
    OM_REP_UPLOADER = 'RMAROM',
    HR_REP_UPLOADER = ' RMARHR',
    FIN_REP_UPLOADER = 'RMARFN',
    HR_LEAVE_SUPER_ADMIN = 'RMASHR',

    //User Roles
    IT_ADMIN_ROLE: 1,
    HR_SUPER_ADMIN_ROLE: 2,
    HR_SITE_ADMIN_ROLE: 3
}
